### ISSUE TITLE
Do not generate files with windows reserved names (CON, PRN, NUL, COM<X>, etc)

### ISSUE THREAD

**Issue by TechnoMancer** [djmcgill/form#12]
Some filenames cannot be used on windows, having modules separated into file with these names when they have such names makes the resulting code unusable on windows.

See the bullet point for reserved names at https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

**Comment by djmcgill** [comment]
Huh this is an interesting one, because if we renamed the modules we'd have to start messing around with renaming the imports too which is just asking for trouble.

We can't even switch to using `mod.rs` because it'd just shift the problem to the directory names.

Is there a way to declare that a module is located at a different path to the usual process?

Otherwise the solution seems to me to be upstream, that svd2rust should not generate modules with reserved names? It's _much_ easier to fix this at the source than to try to do a rename here.

**Comment by TechnoMancer** [comment]
It is possible to use this form of module declaration to name the module something other than the file name: 
```rust
#[path = "foo.rs"]
mod c;
```

See https://doc.rust-lang.org/reference/items/modules.html

**Comment by djmcgill** [comment]
I've been playing around with path attributes and they don't seem to work very well with 2018 edition modules.

My directory is:
![image](https://user-images.githubusercontent.com/1290757/62428521-b1a57280-b6fa-11e9-816e-15c255ad39a4.png)

My main has:
```
#[path = "foo.rs"]
mod bar;

mod baz;
```
where `bar` is our "forbidden" name for this test. All the files in the `foo` directory path need a path attribute.
In `foo_tests.rs`:
```
mod foo_tests_tests;
```
gives the error: 
```
error[E0583]: file not found for module `foo_tests_tests`
 --> src/foo/foo_tests.rs:1:5
  |
1 | mod foo_tests_tests;
  |     ^^^^^^^^^^^^^^^
  |
  = help: name the file either foo_tests_tests.rs or foo_tests_tests/mod.rs inside the directory "src/foo"
```
Even though the same works for `baz` which doesn't have the rename applied.

What this means in practice (as far as I can tell) is that as soon as we apply a rename, then every file and directory below that point in the tree also need to have a path attribute on every `mod` declaration. 
You can see the behaviour here: https://github.com/djmcgill/path-attribute-test

I think the best way to implement it would be that when `mod foo { ... }` is transformed into `mod foo;` [here](https://github.com/djmcgill/form/blob/master/src/util.rs#L119) you would also add a path attribute to it if you knew you were in a renamed branch. It doesn't actually seem that bad to do by adding a bool to the `FileIntoMods` struct.

Unfortunately I don't have time to make the change myself but I would be happy to talk more about it and accept a PR for it.

**Comment by burrbull** [comment]
https://github.com/rust-lang/rust/issues/59345

**Comment by djmcgill** [comment]
Good to know it's considered an issue, I was thinking about raising one. Luckily it doesn't block anything here, just makes it more annoying - renaming just once vs renaming entire branches of the tree.

**Comment by TechnoMancer** [comment]
Are mod.rs style modules not allowed in 2018 edition? 
It might make sense to emit a mod.rs style module for such renamed modules since it will avoid having to add #[path] to all the submodule declarations.
I will have a look at making a change for this next week when I have some time either way.

**Comment by djmcgill** [comment]
You can mix old style modules with no problem.


Both approaches (switching to old style modules, or adding path attributes) will require you to add a bool flag to the Fold struct (more details in my previous comment) so I see them as fairly equivalent.


Personally I would prefer just adding  the rename attributes all the way
down as I feel that's more consistent with the rest of the generated code.

If you try and prefer the mod.rs approach that's fine though I'll be happy to accept it - either way it's temporary until the underlying issue is
fixed.

**Comment by djmcgill** [comment]
Okay I don't know why but I just had 2 much easier solutions pop into my head: 1) have a setting to just pre/append something to the module/folder name (i.e. mod_com), or 2) just don't expand past reserved words. Number 1 doesn't even need to have any windows specific knowledge in, at the cost of tainting all the names which honestly is not a big deal. Both are very easy to implement.

**Comment by TechnoMancer** [comment]
By 2) do you mean not splitting reserved names into separate files?
Yes 1) is likely the easiest solution to allow a project to avoid the problem, however if this changes the actual module names then the difference will leak into the API and if it just changes the filenames then all the #[path] futzing will still be needed.

**Comment by burrbull** [comment]
2) `+`

**Comment by djmcgill** [comment]
For number 2 yes, I meant only doing a partial form-ing, which is at least
better than nothing. You would stop expanding a branch as soon as you hit a
reserved module name down that path.

For number 1, yes I meant an api leaking change since the path nonsense
hasn't changed unfortunately. I suppose if people are already using an
un-expanded version this isn't really worth it.
