### ISSUE TITLE
Option to create a cargo workspace, instead of a single crate

### ISSUE THREAD

**Issue by jamesmunns** [djmcgill/form#2]
I often use form for large amounts of generated code. Unfortunately, a single crate will only ever use a single compilation unit. This is a problem when that crate holds 100kloc-1000kloc. Specifically I have one that I am working on with just over a million lines generated.

It would be nice to have a flag that would generate a cargo workspace, instead of a single crate with modules. This would allow parallel compilation to speed compile times, and hopefully hold less RAM at any single point in time.

Instead of:

```
mod_a/mod.rs
mod_b/mod.rs
lib.rs
```

this would instead create

```
mod_a/lib.rs
mod_a/Cargo.toml
mod_b/lib.rs
mod_b/Cargo.toml
mod_root/lib.rs
mod_root/Cargo.toml
./Cargo.toml
```

Where `mod_root` would be the only crate you would expect to use (all would have to be published, though).

I may attempt to implement this, but I wanted to open an issue to see if you would be interested in supporting two different modes.

**Comment by djmcgill** [comment]
It depends on how common this use case is - I'm happy to link to the fork in the readme but it's not my use case.

Regarding implementation I'm happy to answer questions but probably don't have time to directly do it myself. What is required is to provide a different struct that implements `Folder` similar to how the current `FileIntoMods` does.

Edit: and then after a single recurse (or maybe 2) would call FileIntoMods because presumably you don't want new crates all the way down.

**Comment by jamesmunns** [comment]
No worries! If I get a chance to implement it, I can always fork it off as `form-workspace` or something like that. Thanks for the pointer for where to look :)
